# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
androidx-activity = "1.5.1"
androidx-appcompat = "1.4.2"
androidx-core = "1.8.0"
androidx-fragment = "1.5.1"
androidx-lifecycle = "2.5.1"
androidx-room = "2.4.3"
androidx-test = "1.4.0"
androidx-test-espresso = "3.4.0"
butterknife = "10.2.3"
coroutines = "1.6.4" # https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md
dagger = "2.42"
debugdrawer = "0.9.0"
eventbus = "3.3.1"
google-api-client = "1.34.1"
kotlin = "1.7.10" # https://kotlinlang.org/docs/releases.html#release-details
retrofit2 = "2.9.0"

[libraries]
amazon-appstore-sdk = "com.amazon.device:amazon-appstore-sdk:3.0.2"
androidutils = "com.uwetrottmann.androidutils:androidutils:3.0.0"
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.4.0"
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-paging-runtime-ktx = "androidx.paging:paging-runtime-ktx:3.1.1"
androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-espresso-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-ext-truth = "androidx.test.ext:truth:1.4.0"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-viewpager = "androidx.viewpager:viewpager:1.0.0"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.1.0-beta01"
billing-ktx = "com.android.billingclient:billing-ktx:4.0.0"
butterknife = { module = "com.jakewharton:butterknife", version.ref = "butterknife" }
butterknife-compiler = { module = "com.jakewharton:butterknife-compiler", version.ref = "butterknife" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
debugdrawer-actions = { module = "com.github.lenguyenthanh.debugdrawer:debugdrawer-actions", version.ref = "debugdrawer" }
debugdrawer-base = { module = "com.github.lenguyenthanh.debugdrawer:debugdrawer-base", version.ref = "debugdrawer" }
debugdrawer-commons = { module = "com.github.lenguyenthanh.debugdrawer:debugdrawer-commons", version.ref = "debugdrawer" }
debugdrawer-timber = { module = "com.github.lenguyenthanh.debugdrawer:debugdrawer-timber", version.ref = "debugdrawer" }
debugdrawer-view = { module = "com.github.lenguyenthanh.debugdrawer:debugdrawer-view", version.ref = "debugdrawer" }
findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
firebase = "com.google.firebase:firebase-bom:30.3.1"
firebase-ui-auth = "com.firebaseui:firebase-ui-auth:8.0.0"
flatbuffers = "com.google.flatbuffers:flatbuffers-java:1.12.0"
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "google-api-client" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "google-api-client" }
google-http-client = "com.google.http-client:google-http-client-gson:1.41.8"
greenrobot-eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
greenrobot-eventbus-annotation-processor = { module = "org.greenrobot:eventbus-annotation-processor", version.ref = "eventbus" }
gson = "com.google.code.gson:gson:2.9.1"
junit = "junit:junit:4.13.2"
kotlin-result = "com.michael-bull.kotlin-result:kotlin-result:1.1.16"
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
material = "com.google.android.material:material:1.5.0"
mockito = "org.mockito:mockito-core:4.5.1"
okhttp = "com.squareup.okhttp3:okhttp:4.10.0"
photoview-library = "com.uwetrottmann.photoview:library:1.2.4"
picasso = "com.squareup.picasso:picasso:2.8"
play-services-auth = "com.google.android.gms:play-services-auth:20.2.0"
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
robolectric = "org.robolectric:robolectric:4.8.1"
systembartint = "com.readystatesoftware.systembartint:systembartint:1.0.4"
taptargetview = "com.getkeepsafe.taptargetview:taptargetview:1.13.3"
threetenabp = "com.jakewharton.threetenabp:threetenabp:1.4.0"
threetenbp = "org.threeten:threetenbp:1.6.0"
timber = "com.jakewharton.timber:timber:5.0.1"
tmdb-java = "com.uwetrottmann.tmdb2:tmdb-java:2.8.1" # https://github.com/UweTrottmann/tmdb-java/blob/master/CHANGELOG.md
trakt-java = "com.uwetrottmann.trakt5:trakt-java:6.11.2" # https://github.com/UweTrottmann/trakt-java/blob/master/CHANGELOG.md
truth = "com.google.truth:truth:1.1.3"
